### ISSUE TITLE
Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve '@/KgmWasm/KgmWasmBundle' in '/home/alex/123/src/decrypt'

### ISSUE THREAD

**Issue by IamAlexChang** [ipid/unlock-music#1]
Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve '@/KgmWasm/KgmWasmBundle' in '/home/alex/123/src/decrypt'

**Comment by ipid** [comment]
这里不是主分支，请把 issue 报告给 https://git.unlock-music.dev/um/web。
