### ISSUE TITLE
multi (webpack)-dev-server/client?http://localhost:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

### ISSUE THREAD

**Issue by AsukaLay** [ipid/unlock-music#2]
有一个报错  @/KgmWasm/KgmWasmBundle  引用没有对

ERROR in /music/unlock-music/src/decrypt/kgm_wasm.ts(1,29):
1:29 Cannot find module '@/KgmWasm/KgmWasmBundle' or its corresponding type declarations.
  > 1 | import KgmCryptoModule from '@/KgmWasm/KgmWasmBundle';
      |                             ^
    2 | import { MergeUint8Array } from '@/utils/MergeUint8Array';
    3 | 
    4 | // 每次处理 2M 的数据
ERROR in /music/unlock-music/src/decrypt/qmc_wasm.ts(1,29):
1:29 Cannot find module '@/QmcWasm/QmcWasmBundle' or its corresponding type declarations.
  > 1 | import QmcCryptoModule from '@/QmcWasm/QmcWasmBundle';
      |                             ^
    2 | import { MergeUint8Array } from '@/utils/MergeUint8Array';
    3 | 
    4 | // 每次处理 2M 的数据

**Comment by ipid** [comment]
这里不是主仓库，请把 issue 报告给 [https://git.unlock-music.dev/um/web](https://git.unlock-music.dev/um/web)。
