### ISSUE TITLE
Cannot be deployed correctly

### ISSUE THREAD

**Issue by alexander1wang** [ipid/unlock-music#3]
When executing 'npm run build' "Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve '@/KgmWasm/KgmWasmBundle' in 'xxx'". I have tried to reinstall, modify webpack.config.js file and other methods, but still cannot be correctly deployed, looking forward to your answer

**Comment by ipid** [comment]
I've encountered this issue before, and I think I have a solution that might help. 

The error message you're seeing indicates that you did not build the WASM modules of the project. To deploy the project correctly, you'll need to follow the official build guideline closely, make sure your WASM compilation environment is properly set up, and build the WASM part of the project before running `npm run build`.
